spring:
  profiles.active: local

server:
  port: 8082
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  rabbitmq:
      username: me
      password: 123456
      host: 127.0.0.1
      port: 5672
